### ISSUE TITLE
consul crate doesn't support sending requests with headers

### ISSUE THREAD

**Issue by ceseale** [polyswarm/relay#10]
**Is your feature request related to a problem? Please describe.**
[This](https://github.com/stusmall/consul-rust) consul crate doesn't support sending requests with headers which in problematic in prod.

**Describe the solution you'd like**
We're going to need to fork the repo and add that feature so the `X-Consul-Token` can be added if it's available.

**Comment by ceseale** [comment]
@mjkoo if this sounds okay can you fork the repo to our org for me?

**Comment by ceseale** [comment]
@myhndl :point_up:

**Comment by myhndl** [comment]
https://github.com/polyswarm/consul-rust

**Comment by myhndl** [comment]
Closing in favor of: https://github.com/polyswarm/rust-web3/issues/1
