### ISSUE TITLE
Consul config issues

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/relay#13]
**Describe the bug**
Consul config module has some code smell and is breaking tests

- [x] Depends on environement variables being set, no fallback, everything else is in settings.rs (can set stuff from environment there with override)
- [ ] Returns bare Strings, `.expects()` and `.unwraps()` several times causing potential panics
- [x] eprintln! vs macros from log crate

Our test suite isn't great but the existing mock tests are broken by this

**To Reproduce**
1. `cargo test`

**Comment by myhndl** [comment]
Do any of these issues block development or would you categorize this more as development velocity (see my email) items?

**Comment by mjkoo** [comment]
This blocks #18 which is a "velocity" item, but also could result in reliability issues in relay imo

**Comment by myhndl** [comment]
Not actually a blocker, per: https://github.com/polyswarm/relay/issues/18#issuecomment-438084006

**Comment by myhndl** [comment]
High priority per @mjkoo , moving up in column
