### ISSUE TITLE
Unit tests, lints, cargo fmt in CI

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/relay#14]
**Is your feature request related to a problem? Please describe.**
We should run tests (`cargo test`) lints (`clippy`) and ensure that code is clean via `cargo fmt` (https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server)

**Describe the solution you'd like**
Add all this to CI yml

**Comment by myhndl** [comment]
Can this be closed in favor of https://github.com/polyswarm/relay/issues/18 @mjkoo ?

**Comment by mjkoo** [comment]
Updated description of 18 to cover these items, closing in favor of #18
