### ISSUE TITLE
Minimize chances of missed withdrawals

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/relay#24]
**Is your feature request related to a problem? Please describe.**
Right now we watch for transfer events using the subscribe rpc feature, we should more robustly handle any instances where we might miss transfers

**Describe the solution you'd like**
In addition to eth_subscribe, consider one or both of:

- Periodic polling of event logs since last polled block, ensuring that all transfers that meet confirmation requirements were processed
- A way to manually trigger processing a transaction by providing a txhash, by which we could retrieve the event logs and check reqs / ensure processed

**Describe alternatives you've considered**
In order to miss a transfer >1/3 of verifiers would have to miss it, we could increase number of verifiers to decrease this probability with no code changes.

**Comment by myhndl** [comment]
Spoke with @Rizato , this one is high prio, will move up in column.

**Comment by Rizato** [comment]
Wrapping this part in from #3

>I'm unclear looking at the code what happens if a transaction times out, specifically in the case where a transaction has confirmed on the sidechain and funds are released on mainnet, but gas fees are too high and the tx doesn't confirm. This is mostly theoretical with a 20Gwei default fee, but could result in funds not actually being delivered.
