### ISSUE TITLE
Log level hardcoded to debug

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/relay#28]
**Describe the bug**
Log level is always set to debug, should respect either env var (preferable to match other rust log libs imo) or config value, or at least be set to info or similar.

**Comment by myhndl** [comment]
Other projects support a CLI arg, `--log` to specify level. Let's do the same here with the (admittedly ambiguous) CLI argument.

Lets:
1. [ ] default to info level
1. [ ] override default with env var
1. [ ] override envvar with `--log` CLI arg
