### ISSUE TITLE
Gamma review

### ISSUE THREAD

**Issue by myhndl** [polyswarm/relay#3]
1. ~I'm unclear looking at the code what happens if a transaction times out, specifically in the case where a transaction has confirmed on the sidechain and funds are released on mainnet, but gas fees are too high and the tx doesn't confirm. This is mostly theoretical with a 20Gwei default fee, but could result in funds not actually being delivered.~ Moved to #24 
1. Need to resolve this TODO: https://github.com/polyswarm/contracts/blob/66841d7cbc5ac76a9a675add03839526f4a4afc3/contracts/ERC20Relay.sol#L233
1. If someone tries to withdraw less than the fees from sidechain->mainnet, it's unclear to me what happens. Do they lose those funds?

**Comment by Rizato** [comment]
Updated with github link.
