### ISSUE TITLE
Sign transaction in relay itself

### ISSUE THREAD

**Issue by Rizato** [polyswarm/relay#40]
**Is your feature request related to a problem? Please describe.**
We don't want to store all the relay keymat inside the geth containers on infra.

**Describe the solution you'd like**
Need to be able to decrypt the keyfile, and sign transactions
Then we can use send_raw_transaction to post to geth.

**Additional context**
Blocks Steve

Decrypting in web3.py (pbkdf2 to get key to decrypt eth key inside json blob)
https://github.com/ethereum/eth-keyfile/blob/d8f9ed9e9c232bc69f5b1199f44b5b78c1fa6a34/eth_keyfile/keyfile.py#L151

Signing in web3.py ()
Still looking

Hack found on SO (Just use web3.py in rust) https://ethereum.stackexchange.com/questions/46490/how-to-sign-a-transaction-in-rust

**Comment by scsich** [comment]
I'm not sure that we need to do this today, but it breaks encapsulation between a community and environment wide homechain (e.g. rinkeby). Currently both community relay(s) and rinkeby_homechain a required to have relay key. We can support this for using the same relay keys across 2-3 communities per environment but it quickly becomes unwieldy.

The solution I'd like to see is something where the community service(s) hold on to their own keys. Or maybe this?

https://www.hashicorp.com/blog/using-vault-to-build-an-ethereum-wallet

**Comment by scsich** [comment]
Removing blocker tag for now.

**Comment by mjkoo** [comment]
Implementation of tx signing https://github.com/synlestidae/ethereum-tx-sign/blob/master/src/raw_transaction.rs we could either use this lib or grab that func (it's pretty short), MIT licensed

**Comment by ceseale** [comment]
closed with #44
