### ISSUE TITLE
Investigate sccache

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/relay#46]
**Is your feature request related to a problem? Please describe.**
Relay build times in e2e are pretty long, see if we can set up https://github.com/mozilla/sccache for our CI runners to speed this up

Perhaps relevant to gitlab CI: https://github.com/mozilla/sccache/blob/master/docs/Jenkins.md

Rough plan from quick research:
- [x] Set up s3 bucket for artifacts
- [x] Set `SCCACHE_BUCKET`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` env vars for CI runs
- [x] Install sccache into docker image before cargo steps, fetch static bin from https://github.com/mozilla/sccache/releases probably
- [x] Set `RUSTC_WRAPPER` env var to point to sccache

**Comment by myhndl** [comment]
takes about 30 mins

**Comment by mjkoo** [comment]
Done in #61
