### ISSUE TITLE
If event fired with "removed", stop waiting for confirmations and revoke vote

### ISSUE THREAD

**Issue by myhndl** [polyswarm/relay#5]
Several edge cases here need to make sure we don't lose transfers, related to #1 (closed)

**Comment by myhndl** [comment]
@mjkoo I don't recall exactly what this was about - do you?

**Comment by mjkoo** [comment]
Yes, events can be removed in the case of a fork, we should detect that and reverse our vote / cancel pending votes

**Comment by myhndl** [comment]
Spoke with @Rizato , this one is high prio, will move up in column.
